In [2]:
import numpy as np
import pandas as pd

In [66]:
#read csv file and only select the catrgorical variables
df= pd.read_csv('train.csv', usecols=['X1','X2','X3','X4','X5','X6','X8'])

In [67]:
df.head()

  X1  X2 X3 X4 X5 X6 X8
0  v  at  a  d  u  j  o
1  t  av  e  d  y  l  o
2  w   n  c  d  x  j  x
3  t   n  f  d  x  l  e
4  v   n  f  d  h  d  n

In [68]:
# Now I will check how many unique categories are present in each and every column
for col in df.columns:
    print(col, len(df[col].unique()), 'Labels')

X1 27 Labels
X2 44 Labels
X3 7 Labels
X4 4 Labels
X5 29 Labels
X6 12 Labels
X8 25 Labels

In [69]:
# now we will examine how many columns we will obtain after one hot encoding these variables
pd.get_dummies(df, drop_first=True).shape

(4209, 141)

In [70]:
#let's find the 10 most frequent categories in column X2 
df.X2.value_counts().sort_values(ascending=False).head(20)

X2
as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
k       25
i       25
b       21
ao      20
z       19
ag      19
Name: count, dtype: int64

In [71]:
#you can see above that each category is repeated for the following above number of times
# now we will take top most frequent variables and make the rest as zero to avoid from high dimentionality

In [72]:
# now let's make a list with the most frequent categories of the variable
top_10= [x for x in df.X2.value_counts().sort_values(ascending=False).head(10).index]
top_10

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [73]:
# Now I will make the 10 binary variables
# it will find where label will be equal to column vlaue it will replace it with 1 else 0

for label in top_10:
    df[label]= np.where(df['X2']==label, 1,0)

df[['X2']+ top_10].head(20)

    X2  as  ae  ai  m  ak  r  n  s  f  e
0   at   0   0   0  0   0  0  0  0  0  0
1   av   0   0   0  0   0  0  0  0  0  0
2    n   0   0   0  0   0  0  1  0  0  0
3    n   0   0   0  0   0  0  1  0  0  0
4    n   0   0   0  0   0  0  1  0  0  0
5    e   0   0   0  0   0  0  0  0  0  1
6    e   0   0   0  0   0  0  0  0  0  1
7   as   1   0   0  0   0  0  0  0  0  0
8   as   1   0   0  0   0  0  0  0  0  0
9   aq   0   0   0  0   0  0  0  0  0  0
10   r   0   0   0  0   0  1  0  0  0  0
11   e   0   0   0  0   0  0  0  0  0  1
12  ai   0   0   1  0   0  0  0  0  0  0
13   e   0   0   0  0   0  0  0  0  0  1
14  as   1   0   0  0   0  0  0  0  0  0
15  ak   0   0   0  0   1  0  0  0  0  0
16   e   0   0   0  0   0  0  0  0  0  1
17  as   1   0   0  0   0  0  0  0  0  0
18   m   0   0   0  1   0  0  0  0  0  0
19  ak   0   0   0  0   1  0  0  0  0  0

In [74]:
# Now get whole set of dummy variables for all the categorical columns
def one_hot_encoding(df,col_name,top_X_labels):
    #Func to create the dummy variables for most frequest labels
    #we can vary the most frequent number of labels that we chosse to encode
    for label in top_X_labels:
        df[col_name+'_'+label]= np.where(df[col_name]==label, 1,0)

#read the data again
df= pd.read_csv('train.csv',usecols=['X1','X2','X3','X4','X5','X6','X8'])
#encode X2 into 10 most frequent categories
one_hot_encoding(df,'X2', top_10)

df.head()

,X1,X2,X3,X4,X5,X6,X8,X2_as,X2_ae,X2_ai,X2_m,X2_ak,X2_r,X2_n,X2_s,X2_f,X2_e
0,v,at,a,d,u,j,o,0,0,0,0,0,0,0,0,0,0
1,t,av,e,d,y,l,o,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,x,0,0,0,0,0,0,1,0,0,0
3,t,n,f,d,x,l,e,0,0,0,0,0,0,1,0,0,0
4,v,n,f,d,h,d,n,0,0,0,0,0,0,1,0,0,0

In [75]:
columns= df.columns
columns

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X2_as', 'X2_ae', 'X2_ai',
       'X2_m', 'X2_ak', 'X2_r', 'X2_n', 'X2_s', 'X2_f', 'X2_e'],
      dtype='object')

In [76]:


# now take only first 7 columns
columns= df.columns[:7].tolist()
columns

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']

In [83]:
for col in columns:
    print(col)
    top_10=[x for x in df[col].value_counts().sort_values(ascending=False).index]
    one_hot_encoding(df,X,top_10)

df.head(10)

X1
X2
X3
X4
X5
X6
X8

,X1,X2,X3,X4,X5,X6,X8,X2_as,X2_ae,X2_ai,...,X1_at,X1_al,X1_an,X1_av,X1_ah,X1_au,X1_am,X1_af,X1_ar,X1_ad
0,v,at,a,d,u,j,o,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,t,av,e,d,y,l,o,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,x,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,e,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,v,n,f,d,h,d,n,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,b,e,c,d,g,h,s,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,r,e,f,d,f,h,s,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,l,as,f,d,f,j,a,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,s,as,e,d,f,i,h,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,b,aq,c,d,f,a,e,0,0,0,...,0,0,0,0,0,0,0,0,0,0